development: 
  adapter: postgresql 
  encoding: unicode 
  database: timetracker_dev
  host: localhost 
  pool: 5 
  username: pallavi 
  password: 1234

production: 
  adapter: postgresql 
  encoding: unicode 
  database: timetracker_prod
  host: localhost 
  pool: 5 
  username: pallavi 
  password: 1234 

test: 
  adapter: postgresql 
  encoding: utf8
  database: timetracker_test
  pool: 5
  username: pallavi 
  password: 1234